name: Training with inputs parameters

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: do a ls
        run: ls

      - name: echo Branch
        run: echo "Testing branch"